---
- hosts: webservers
  become: yes
  tasks: 
  - name: install java8 on ubuntu16
    apt:
      name: "{{ javaonubuntu }}"
      state: present
    when: ansible_os_family =="Debian"

  - name: install java7 on amazon
    yum:
      name: "{{ javaonamazon }}"
      state: present
    when: ansible_os_family =="RedHat"
 
